### ISSUE TITLE
TypeError: unexpected kwargs: {'heartbeat_interval': 0}

### ISSUE THREAD

**Issue by raj-kiran-p** [albertomr86/python-logging-rabbitmq#13]
I always get this error.

The error was from line 101 in handler,py.   
But I think it is because of the line 62   
self.connection_params.update(dict(host=host, port=port, heartbeat_interval=0))

Just go through this [Pika Documentation](https://pika.readthedocs.io/en/stable/modules/parameters.html)

connection_params does not have `heartbeat_interval`

**Comment by albertomr86** [comment]
Thanks for spotted this. 
Seems that option not longer exists in the last version of pika, I'll do a full review of the config.

**Comment by sulsj** [comment]
Any update on this issue?

**Comment by albertomr86** [comment]
oh, sorry. I'm getting back to work these days.
I will provide support during this weekend.
Thanks

**Comment by Ghost93** [comment]
Any news on this?

**Comment by albertomr86** [comment]
Hi, thank you for the PR. I'm looking at it, and also I'm sorry for the delay, I've been planning a major release trying to include unit tests. I definitely will prioritize the PR.

**Comment by Ghost93** [comment]
Great. Thank you @albertomr86

**Comment by albertomr86** [comment]
Hi.
I am pleased to announce the release of version 2.0.0 that includes this fix.
Thank you for collaborating.

**Comment by mishravishal** [comment]
Just updated rabbitmq server to 3.8.4 on ubuntu 18.04 and seeing the error above for the version installed from pypi.
Exception- unexpected kwargs: {'heartbeat_interval': 60}

How may I install the latest version to fix this?
