### ISSUE TITLE
RabbitMQ server closes the connection because not receiving heartbeat

### ISSUE THREAD

**Issue by yuanli-cn** [albertomr86/python-logging-rabbitmq#17]
Hi Albert,
Similar to issue https://github.com/pika/pika/issues/1104.
After digging into Pika and RabbitMQ, I find with BlockedConnection, pika will not automatically send out the heartbeat. The heartbeat event will only be handled/sent in "start_consuming" and "process_data_events".
For consumer, we will use "start_consuming", there will not be such issue. But for producer, normally we won't call "process_data_events" specifically, it will only be called when we call "basic_publish".
Let's say we set "heartbeat" to 20s, if we don't log any message within 3x10s, the server would close the connection. (Different version of RabbitMQ might have different behaviors, some might take 3x20s)
I didn't see anyone report this issue or talk this on the internet, so I'm not sure if my understanding is correct. Look forward to your response.
Thanks in advance.

**Comment by albertomr86** [comment]
Hello.

After being off for a good amount of days, I'm planning to start doing clean up of issues.

Meanwhile, if you have some working code, please, add an MR, and I will be happy to review it.

Thanks.

**Comment by yuanli-cn** [comment]
> Hello.
> 
> After being off for a good amount of days, I'm planning to start doing clean up of issues.
> 
> Meanwhile, if you have some working code, please, add an MR, and I will be happy to review it.
> 
> Thanks.

I just tried to use SelectConnection instead of BlockedConnection

**Comment by oyld** [comment]
I encountered the same problem.
The client not send heartbeat to rabbitmq in 60s, and the server close the connection. Server log is: missed heartbeats from client, timeout: 60s

**Comment by santhoshsonti4** [comment]
Any update on this issue?

**Comment by albertomr86** [comment]
I opened the PR #19 to work on this issue. I'm running some tests.
