### ISSUE TITLE
ImportError: No module named 'compat'

### ISSUE THREAD

**Issue by sactre** [albertomr86/python-logging-rabbitmq#2]
When I use the library I see an Exception:

File "/usr/local/lib/python3.4/dist-packages/python_logging_rabbitmq/__init__.py", line 2, in <module>
    from .formatters import JSONFormatter  # noqa: F401
  File "/usr/local/lib/python3.4/dist-packages/python_logging_rabbitmq/formatters.py", line 4, in <module>
    from compat import json
ImportError: No module named 'compat'

are some wrong in __ini__?

Regards and thank you for your library.

**Comment by albertomr86** [comment]
'compat' is not itself a dependency but the compat.py file, I made changes to import it locally ('.compat').
Could you try with version 1.0.5 that I have released?
Thanks.

**Comment by sactre** [comment]
Yes, the fix works.
Thanks. Gracias
