### ISSUE TITLE
wait for logs to be sent in RabbitMQHandlerOneWay before exiting python ?

### ISSUE THREAD

**Issue by BenjaminSchmitt** [albertomr86/python-logging-rabbitmq#9]
Hi,

Thank you for your great package.

Is there any way to wait for logs to be sent in RabbitMQHandlerOneWay before exiting python ? Naive method could be to wait a few seconds (```time.sleep(2)```) but there is maybe a better method.

Thanks a lot.

**Comment by albertomr86** [comment]
Hello. Thanks for the interest. I definitely will look at this.

**Comment by albertomr86** [comment]
Archivable after PR #25
